### ISSUE TITLE
Avi creates case study drafts

### ISSUE THREAD

**Issue by avidrucker** [avidrucker/a12y-exp#18]
Question: What is your single source of truth? Where are these documents? In Google Docs or Figma?
- [ ] Avi locates the documents
- [ ] Avi chooses 1 location for these documents
- [ ] Avi notes where these documents are here
- [x] Avi writes HE case study draft 1
- [x] Avi writes TD case study draft 1
- [x] Avi writes AF case study draft 1
